<?php

namespace App\Http\Controllers;

use App\Models\Assignment;
use App\Models\Notification;
use App\Models\Schedule;
use App\Models\User;
use App\Services\FonnteService;
use App\Services\SchedulerService;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Inertia\Inertia;

class ScheduleController extends Controller
{
    /**
     * Display a listing of schedules.
     */
    public function index()
    {
        $schedules = Schedule::with('assignments.user')
            ->orderBy('date', 'desc')
            ->get()
            ->groupBy(function ($date) {
                return Carbon::parse($date->date)->format('F Y');
            });

        return Inertia::render('Schedules/Index', [
            'schedules' => $schedules,
            'users' => User::all()->map(function ($user) {
                return [
                    'id' => $user->id,
                    'name' => $user->name,
                    'jenis_pegawai' => $user->jenis_pegawai,
                    'jenis_jabatan' => $user->jenis_jabatan,
                    'gender' => $user->gender,
                ];
            }),
        ]);
    }

    /**
     * Generate schedules for a given date range.
     */
    public function generate(Request $request, SchedulerService $scheduler)
    {
        $request->validate([
            'start_date' => 'required|date|after_or_equal:today',
            'end_date' => 'required|date|after_or_equal:start_date',
        ], [
            'start_date.after_or_equal' => 'Tanggal mulai tidak boleh di masa lalu.',
        ]);

        $scheduler->generate(
            Carbon::parse($request->start_date),
            Carbon::parse($request->end_date)
        );

        return redirect()->back()->with('success', 'Jadwal apel berhasil dibuat.');
    }

    /**
     * Broadcast schedule to WhatsApp group via Fonnte.
     * Menggunakan strategi "Jalur Aman": 1 pesan ke grup (bukan ke individu).
     */
    public function broadcast(Request $request, FonnteService $fonnte)
    {
        $request->validate(['schedule_id' => 'required|exists:schedules,id']);

        $schedule = Schedule::with('assignments.user')->find($request->schedule_id);

        // Format pesan untuk grup WhatsApp
        $tanggal = Carbon::parse($schedule->date)->format('d M Y');
        $hari = $schedule->type === 'senin' ? 'Senin' : 'Jumat';

        $message = "📢 *JADWAL APEL PENGADILAN AGAMA PENAJAM*\n\n";
        $message .= "🗓️ *Tanggal:* {$tanggal} ({$hari})\n\n";
        $message .= "━━━━━━━━━━━━━━━━━━━━\n";
        $message .= "📋 *PENUGASAN:*\n";

        foreach ($schedule->assignments as $assignment) {
            $role = $assignment->role;
            $name = $assignment->user->name ?? '-';
            $message .= "• {$role}: {$name}\n";
        }

        $message .= "━━━━━━━━━━━━━━━━━━━━\n";
        $message .= "💪 *Tetap semangat dan hadir tepat waktu!*\n\n";
        $message .= '_Generated by APEL System_';

        // Ambil konfigurasi dari .env
        $token = env('FONNTE_TOKEN');
        $target = env('FONNTE_TARGET_GROUP');

        $status = 'simulasi';
        $success = false;

        if ($token && $target) {
            // Kirim ke grup
            $success = $fonnte->sendToGroup($target, $message);
            $status = $success ? 'berhasil terkirim ke grup' : 'gagal terkirim';
        } elseif (! $token) {
            $status = 'simulasi (Token Fonnte belum disetting di .env)';
        } elseif (! $target) {
            $status = 'simulasi (Target Group belum disetting di .env)';
        }

        // Log untuk debugging
        \Log::info('Fonnte Broadcast', [
            'schedule_id' => $schedule->id,
            'success' => $success,
            'status' => $status,
        ]);

        $notificationType = ($success) ? 'success' : 'warning';

        return redirect()->back()->with($notificationType, "Notifikasi {$status}");
    }

    /**
     * Broadcast schedule to individual WhatsApp numbers via Fonnte.
     */
    public function broadcastIndividual(Request $request, FonnteService $fonnte)
    {
        $request->validate(['schedule_id' => 'required|exists:schedules,id']);

        $schedule = Schedule::with('assignments.user')->find($request->schedule_id);
        $token = env('FONNTE_TOKEN');

        $successCount = 0;
        $failCount = 0;
        $noPhoneCount = 0;

        if (! $token) {
            return redirect()->back()->with('error', 'Token Fonnte belum disetting di .env');
        }

        foreach ($schedule->assignments as $assignment) {
            $user = $assignment->user;

            if (! $user || ! $user->phone) {
                $noPhoneCount++;

                continue;
            }

            // Format pesan personal
            $message = "Assalamu'alaikum Wr. Wb.\n\n";
            $message .= "Bapak/Ibu *{$user->name}*,\n\n";
            $message .= "📅 *JADWAL APEL*\n";
            $message .= 'Tanggal: '.Carbon::parse($schedule->date)->format('d M Y')."\n";
            $message .= 'Jenis: '.ucfirst($schedule->type)."\n";
            $message .= "Tugas: *{$assignment->role}*\n\n";
            $message .= "Mohon hadir tepat waktu.\n\n";
            $message .= "Wassalamu'alaikum Wr. Wb.\n\n";
            $message .= '_APEL System - Pengadilan Agama Penajam_';

            $sent = $fonnte->sendToIndividual($user->phone, $message);

            if ($sent) {
                $successCount++;
            } else {
                $failCount++;
            }

            // Delay untuk menghindari rate limit
            usleep(500000); // 0.5 detik
        }

        $summary = "Berhasil: {$successCount}, Gagal: {$failCount}, Tanpa HP: {$noPhoneCount}";

        return redirect()->back()->with('success', "Notifikasi individual: {$summary}");
    }

    /**
     * Broadcast to all assigned users (with rate limit protection).
     */
    public function broadcastAll(Request $request, FonnteService $fonnte)
    {
        $request->validate(['schedule_id' => 'required|exists:schedules,id']);

        $schedule = Schedule::with('assignments.user')->find($request->schedule_id);
        $token = env('FONNTE_TOKEN');

        if (! $token) {
            return redirect()->back()->with('error', 'Token Fonnte belum disetting di .env');
        }

        $successCount = 0;
        $failCount = 0;
        $noPhoneCount = 0;

        foreach ($schedule->assignments as $assignment) {
            $user = $assignment->user;

            if (! $user || ! $user->phone) {
                $noPhoneCount++;

                continue;
            }

            $message = "Assalamu'alaikum Wr. Wb.\n\n";
            $message .= "Bapak/Ibu *{$user->name}*,\n\n";
            $message .= "📅 *JADWAL APEL*\n";
            $message .= 'Tanggal: '.Carbon::parse($schedule->date)->format('d M Y')."\n";
            $message .= "Tugas: *{$assignment->role}*\n\n";
            $message .= "Mohon hadir tepat waktu.\n\n";
            $message .= '_APEL System_';

            $sent = $fonnte->sendToIndividual($user->phone, $message);

            if ($sent) {
                $successCount++;
            } else {
                $failCount++;
            }

            // Delay untuk menghindari rate limit
            usleep(500000); // 0.5 detik
        }

        $summary = "Berhasil: {$successCount}, Gagal: {$failCount}, Tanpa HP: {$noPhoneCount}";

        return redirect()->back()->with('success', "Broadcast selesai: {$summary}");
    }

    /**
     * Test Fonnte connection.
     */
    public function testConnection(FonnteService $fonnte)
    {
        $result = $fonnte->testConnection();

        if (request()->expectsJson()) {
            return response()->json($result);
        }

        if ($result['success']) {
            $message = '✅ Koneksi Fonnte berhasil!';
            if (isset($result['device'])) {
                $message .= ' Device: '.($result['device']['phone'] ?? 'Unknown');
            }

            return redirect()->back()->with('success', $message);
        }

        return redirect()->back()->with('error', '❌ Koneksi Fonnte gagal: '.$result['message']);
    }

    /**
     * Check Fonnte quota/usage.
     */
    public function checkQuota(FonnteService $fonnte)
    {
        $result = $fonnte->checkQuota();

        if (request()->expectsJson()) {
            return response()->json($result);
        }

        if ($result['success']) {
            $quota = $result['quota'] ?? [];
            $remaining = $quota['remaining'] ?? 'Unknown';
            $total = $quota['total'] ?? 'Unknown';

            return redirect()->back()->with('success', "📊 Info Fonnte - Sisa Kuota: {$remaining}/{$total} pesan");
        }

        return redirect()->back()->with('error', '❌ Gagal mengambil info kuota: '.$result['message']);
    }

    /**
     * Delete a schedule.
     */
    public function destroy(Schedule $schedule)
    {
        // Delete related notification records first
        $schedule->notifications()->delete();

        // Delete related assignment records
        $schedule->assignments()->delete();

        // Delete the schedule
        $schedule->delete();

        return redirect()->back()->with('success', 'Jadwal apel dan data terkait berhasil dihapus.');
    }

    /**
     * Force send notification immediately, bypassing scheduled time.
     */
    public function forceSendManual(Request $request, FonnteService $fonnte)
    {
        $request->validate(['schedule_id' => 'required|exists:schedules,id']);

        $schedule = Schedule::with('assignments.user')->find($request->schedule_id);

        // Format pesan untuk grup WhatsApp
        $tanggal = Carbon::parse($schedule->date)->format('d M Y');
        $hari = $schedule->type === 'senin' ? 'Senin' : 'Jumat';

        $message = "📢 *JADWAL APEL PENGADILAN AGAMA PENAJAM* (Pengiriman Manual)\n\n";
        $message .= "🗓️ *Tanggal:* {$tanggal} ({$hari})\n\n";
        $message .= "━━━━━━━━━━━━━━━━━━━━\n";
        $message .= "📋 *PENUGASAN:*\n";

        foreach ($schedule->assignments as $assignment) {
            $role = $assignment->role;
            $name = $assignment->user->name ?? '-';
            $message .= "• {$role}: {$name}\n";
        }

        $message .= "━━━━━━━━━━━━━━━━━━━━\n";
        $message .= "💪 *Tetap semangat dan hadir tepat waktu!*\n\n";
        $message .= '_Generated by APEL System_';

        $token = env('FONNTE_TOKEN');
        $target = env('FONNTE_TARGET_GROUP');

        $status = 'simulasi';
        $success = false;

        if ($token && $target) {
            $success = $fonnte->sendToGroup($target, $message);
            $status = $success ? 'berhasil terkirim ke grup' : 'gagal terkirim';

            // Update notification status if successful
            if ($success) {
                $schedule->update([
                    'notification_status' => 'sent',
                    'notification_sent_at' => now(),
                    'is_auto_notification' => false,
                ]);
            }
        } elseif (! $token) {
            $status = 'simulasi (Token Fonnte belum disetting di .env)';
        } elseif (! $target) {
            $status = 'simulasi (Target Group belum disetting di .env)';
        }

        Log::info('Fonnte Force Send Manual', [
            'schedule_id' => $schedule->id,
            'success' => $success,
            'status' => $status,
        ]);

        $notificationType = $success ? 'success' : 'warning';

        return redirect()->back()->with($notificationType, "Notifikasi manual {$status}");
    }

    /**
     * Update petugas (assignments) for a schedule.
     */
    public function updatePetugas(Request $request, Schedule $schedule)
    {
        \Log::info('updatePetugas called', [
            'schedule_id' => $schedule->id,
            'assignments' => $request->assignments,
        ]);

        $validated = $request->validate([
            'assignments' => 'required|array',
            'assignments.*.id' => 'required|exists:assignments,id',
            'assignments.*.user_id' => 'required|integer|exists:users,id',
            'assignments.*.role' => 'required|string|max:255',
        ]);

        \Log::info('Validation passed', ['validated' => $validated]);

        foreach ($validated['assignments'] as $assignmentData) {
            $assignment = Assignment::find($assignmentData['id']);
            if ($assignment && $assignment->schedule_id === $schedule->id) {
                $oldUserId = $assignment->user_id;
                $newUserId = $assignmentData['user_id'];

                if ($oldUserId != $newUserId) {
                    $assignment->update([
                        'user_id' => $newUserId,
                        'role' => $assignmentData['role'],
                    ]);
                    \Log::info('Assignment updated', ['assignment_id' => $assignment->id, 'old_user' => $oldUserId, 'new_user' => $newUserId]);
                }
            }
        }

        // Reset notification status if assignments changed
        $schedule->update(['notification_status' => 'pending']);

        return Inertia::back()->with('success', 'Petugas berhasil diperbarui.');
    }
}
